apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-lockdown-secrets
  namespace: lockdown-secrets
subjects:
- kind: ServiceAccount
  name: sa-lockdown
roleRef:
  kind: Role
  name: role-lockdown-secrets
  apiGroup: rbac.authorization.k8s.io
